export default [
  {
    id: 1,
    title: "Single Digit",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-one.png",
  },
  {
    id: 2,
    title: "Single Digit Bulk",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-one.png",
  },
  {
    id: 3,
    title: "Single Pana",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-dreamstale-lineal-dreamstale/32/000000/external-ace-of-spades-gambling-dreamstale-lineal-dreamstale-3.png",
  },
  {
    id: 4,
    title: "Single Pana Bulk",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-dreamstale-lineal-dreamstale/32/000000/external-ace-of-spades-gambling-dreamstale-lineal-dreamstale-3.png",
  },
  {
    id: 5,
    title: "Jodi Digits",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-two.png",
  },
  {
    id: 6,
    title: "Jodi Digits Bulk",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-two.png",
  },
  {
    id: 7,
    title: "Double Pana",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-bearicons-detailed-outline-bearicons/64/000000/external-8-Ace-of-Spades-playing-cards-bearicons-detailed-outline-bearicons.png",
  },
  {
    id: 8,
    title: "Double Pana Bulk",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-bearicons-detailed-outline-bearicons/64/000000/external-8-Ace-of-Spades-playing-cards-bearicons-detailed-outline-bearicons.png",
  },
  {
    id: 9,
    title: "Triple Pana",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-bearicons-detailed-outline-bearicons/64/000000/external-52-Three-of-Spades-playing-cards-bearicons-detailed-outline-bearicons.png",
  },
  {
    id: 10,
    title: "Penal Group",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/ios/50/000000/meeting-room.png",
  },
  {
    id: 11,
    title: "Red Brackets",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-icongeek26-glyph-icongeek26/64/000000/external-casino-casino-icongeek26-glyph-icongeek26.png",
  },
  {
    id: 12,
    title: "SP DP TP",
    rate: "Rs 9.5 of 1 Rs",
    icon: "https://img.icons8.com/external-icongeek26-glyph-icongeek26/64/000000/external-casino-casino-icongeek26-glyph-icongeek26.png",
  },
  {
    id: 13,
    title: "Choice Pana SPDP",
    rate: "Rs 95 of 1 Rs",
    icon: "https://img.icons8.com/ios/50/000000/cards.png",
  },
  {
    id: 14,
    title: "SP Motor",
    rate: "Rs 150 of 1 Rs",
    icon: "https://img.icons8.com/ios/50/000000/slot-machine.png",
  },
  {
    id: 15,
    title: "DP Motor",
    rate: "Rs 300 of 1 Rs",
    icon: "https://img.icons8.com/external-icongeek26-glyph-icongeek26/64/000000/external-casino-casino-icongeek26-glyph-icongeek26.png",
  },
  {
    id: 16,
    title: "Odd Even",
    rate: "Rs 1000 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-cubes.png",
  },
  {
    id: 17,
    title: "Two Digits Panel",
    rate: "Rs 10000 of 1 Rs",
    icon: "https://img.icons8.com/windows/32/000000/dice-two.png",
  },
];
