export default [
  {
    id: 1,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
  {
    id: 2,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
  {
    id: 3,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
  {
    id: 4,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
  {
    id: 5,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
  {
    id: 6,
    gameName: "LATA MORNING",
    openBid: "10:50 AM",
    closBid: "11:50 AM",
    status: "Running Now",
    btnTitle: "Play Now",
  },
];
